version: '3.8'
services:
  nest-tutorial: 
    image: nest-tutorial:0.1
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:15.6
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'